let words = [
    "ABERRATION", "ACRIMONIOUS", "AMBIGUOUS", "ANACHRONISTIC", "ANTEDILUVIAN",
    "APOCRYPHAL", "CAPRICIOUS", "CHIAROSCURO", "CLANDESTINE", "CONFLAGRATION",
    "CYNOSURE", "DEFENESTRATION", "DIAPHANOUS", "DISCOMBOBULATE", "EBULLIENT",
    "EPHEMERAL", "EQUIVOCATE", "EXACERBATE", "EXTEMPORANEOUS", "FASTIDIOUS",
    "FECKLESS", "FELICITOUS", "GARRULOUS", "GESTICULATE", "GREGARIOUS",
    "HAPLESS", "ICONOCLAST", "INEFFABLE", "INEXORABLE", "INTRANSIGENT",
    "LABYRINTHINE", "LANGUOROUS", "LUMINOUS", "MELLIFLUOUS", "MENDACIOUS",
    "MERCURIAL", "OBFUSCATE", "OBSTREPEROUS", "OPULENT", "OSTENTATIOUS",
    "PALIMPSEST", "PANACEA", "PARADIGM", "PARADOXICAL", "PERFUNCTORY",
    "PERSPICACIOUS", "PHANTASMAGORIA", "PLENIPOTENTIARY", "PRECARIOUS", "QUIXOTIC",
    "RAPACIOUS", "RECALCITRANT", "REPROBATE", "RESPLENDENT", "RETICENT",
    "SAGACIOUS", "SALUBRIOUS", "SANGUINE", "SARDONIC", "SERENDIPITY",
    "SOLIPSISTIC", "STENTORIAN", "SUPERCILIOUS", "SYCOPHANT", "TENEBROUS",
    "TREPIDATION", "UBIQUITOUS", "UMBRAGE", "UNCTUOUS", "UNFETTERED",
    "UNREQUITED", "VACILLATE", "VERISIMILITUDE", "VEXATIOUS", "VICARIOUS",
    "VITUPERATE", "VOCIFEROUS", "VOLATILE", "XENOPHOBIC", "ZEITGEIST",
    "ZEPHYR", "ZIGGURAT", "ZEPHYR", "ZENITH", "ZIRCONIUM",
    "ZUGZWANG", "ZYDECO", "ZYMURGY", "ABNEGATION", "ACQUIESCE",
    "AUSPICIOUS", "BELLICOSE", "CALLIPYGIAN", "CASTIGATE", "COLLOQUY",
    "DEFENESTRATE", "DESUETUDE", "EPHEMERAL", "EXACERBATE", "OBFUSCATE"
]

export { words };